// Given a string, we have to find out all subsequences of it.
// A String is a subsequence of a given String,
//  that is generated by deleting some character of a given string without changing its order.

#include<bits/stdc++.h>
using namespace std;

void printSubsequence(string s1, string s2)
{
    if(s1.empty())
    {
        cout<<s2<<"\n";
        return;
    }
    printSubsequence(s1.substr(1), s2 + s1[0]);
    printSubsequence(s1.substr(1), s2);
}

int main()
{
    string s1 = "123";
    string s2 = "";

    printSubsequence(s1,s2);
    return 0;
}